# Generated by Django 5.1.4 on 2024-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('formal', 'Formal'), ('sports', 'Sports')], default='sneakers', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=2083, null=True)),
            ],
        ),
    ]
